services:

  ## In Types ##
  create.intype.command.handler:
    class: Mateu\Backend\InType\Application\Create\CreateInTypeCommandHandler
    arguments: ['@intype.creator']
    tags:
      - { name: command_handler, handles: Mateu\Backend\InType\Application\Create\CreateInTypeCommand }

