services:
    Mateu\Backend\Explotation\Application\GetAll\GetExplotationsQueryHandler:
        tags: [{ name: messenger.message_handler, bus: query.bus }]
        # prevent handlers from being registered twice (or you can remove
        # the MessageHandlerInterface that autoconfigure uses to find handlers)
        autoconfigure: false

