services:

  Mateu\Backend\Explotation\Domain\ExplotationRepositoryInterface: '@Mateu\Backend\Explotation\Infraestructure\ExplotationRepository'
  Mateu\Backend\Animal\Domain\AnimalRepository: '@Mateu\Backend\Animal\Infraestructure\AnimalRepositoryMysql'
  Mateu\Backend\Supplier\Domain\SupplierRepositoryInterface: '@Mateu\Backend\Supplier\Infraestructure\SupplierRepository'
  Mateu\Backend\Purchaser\Domain\PurchaserRepositoryInterface: '@Mateu\Backend\Purchaser\Infraestructure\PurchaserRepository'
