knp_snappy:
    process_timeout: 60
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:
            - { name: 'viewport-size', value: '1024x768' }
            - { name: 'page-size', value: 'A4' }
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
