framework:
    messenger:
        transports:
             amqp: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'Mateu\Backend\Notification\Application\Create\NotificationCommand': amqp #name of the transport
