framework:
    messenger:
        buses:
            command.bus:
                middleware:
                    - Mateu\Shared\Application\Bus\Middleware\AuditMiddleware
            event.bus:
                default_middleware: allow_no_handlers
            query.bus: ~
        default_bus: command.bus
        routing:
            Mateu\Backend\Notification\Application\Create\NotificationCommand: amqp
        transports:
            amqp: "%env(MESSENGER_TRANSPORT_DSN)%"
