controllers:
    resource: ../../src/Infraestructure/Controller/
    type: annotation
    prefix: /admin

controllers_ha:
    resource: ../../src/Backend/
    type: annotation
    prefix: /admin

root:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /admin
        permanent: true
